
# The PID gains and controller settings must be saved in a yaml file that gets loaded
# to the param server via the roslaunch file (mobile_control.launch).

mobile:
  # Publish all joint states -----------------------------------
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Effort Controllers ---------------------------------------
  leftFrontWheel_controller:
    type: my_controller_pkg/EffortTestController
    joints:
      - wljf
    # type: effort_controllers/JointEffortController
    # joint: wljf
    # pid: {p: 100.0, i: 0.1, d: 10.0}
    
  leftBackWheel_controller:
    type: effort_controllers/JointEffortController
    joint: wljb
    pid: {p: 100.0, i: 0.1, d: 10.0}

  rightFrontWheel_controller:
    type: effort_controllers/JointEffortController
    joint: wrjf
    pid: {p: 100.0, i: 0.1, d: 10.0}

  rightBackWheel_controller:
    type: effort_controllers/JointEffortController
    joint: wrjb
    pid: {p: 100.0, i: 0.1, d: 10.0}

  # Arm Controllers ---------------------------------------
  joint_1_controller:
    type: effort_controllers/JointEffortController
    joint: m_joint_1
    pid: {p: 100.0, i: 0.1, d: 10.0}

  joint_2_controller:
    type: effort_controllers/JointEffortController
    joint: m_joint_2
    pid: {p: 100.0, i: 0.1, d: 10.0}

  joint_3_controller:
    type: effort_controllers/JointEffortController
    joint: m_joint_3
    pid: {p: 100.0, i: 0.1, d: 10.0}

  joint_4_controller:
    type: effort_controllers/JointEffortController
    joint: m_joint_4
    pid: {p: 100.0, i: 0.1, d: 10.0}

  joint_gripper_controller:
    type: effort_controllers/JointEffortController
    joint: m_joint_5
    pid: {p: 100.0, i: 0.1, d: 10.0}
