
# The PID gains and controller settings must be saved in a yaml file that gets loaded
# to the param server via the roslaunch file (mobile_control.launch).

mobile:
  # Publish all joint states -----------------------------------
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Effort Controllers ---------------------------------------
  leftFrontWheel_controller:
    type: effort_controllers/JointEffortController
    joint: wljf
    pid: {p: 100.0, i: 0.1, d: 10.0}
    
  leftBackWheel_controller:
    type: effort_controllers/JointEffortController
    joint: wljb
    pid: {p: 100.0, i: 0.1, d: 10.0}

  rightFrontWheel_controller:
    type: effort_controllers/JointEffortController
    joint: wrjf
    pid: {p: 100.0, i: 0.1, d: 10.0}

  rightBackWheel_controller:
    type: effort_controllers/JointEffortController
    joint: wrjb
    pid: {p: 100.0, i: 0.1, d: 10.0}

  # Arm Controllers ---------------------------------------
  joint_1_controller:
    # type: my_controller_pkg/WheelController
    # joint: m_joint_1
    # Kp: 0.1
    # Ki: 0.0
    # Kd: 0.001
    # clamp_iMax: 100.0
    # has_position_limits: false
    # has_velocity_limits: true
    # has_acceleration_limits: false
    # has_jerk_limits: false
    # has_effort_limits: true
    # max_velocity: 2.0
    # max_effort: 6.0
    type: my_controller_pkg/ArmController
    joint: m_joint_1
    Kp: 10.0
    Ki: 0.1
    Kd: 1.0
    clamp_iMax: 100.0
    has_position_limits: true
    has_velocity_limits: false
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: true
    min_position: -3.1416
    max_position: 3.1416
    max_effort: 6.0

  joint_2_controller:
    type: my_controller_pkg/ArmController
    joint: m_joint_2
    Kp: 100.0
    Ki: 5.0
    Kd: 10.0
    clamp_iMax: 100.0
    has_position_limits: true
    has_velocity_limits: false
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: true
    min_position: -1.5708
    max_position: 1.5708
    max_effort: 6.0

  joint_3_controller:
    type: my_controller_pkg/ArmController
    joint: m_joint_3
    Kp: 10.0
    Ki: 0.1
    Kd: 1.0
    clamp_iMax: 100.0
    has_position_limits: true
    has_velocity_limits: false
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: true
    min_position: -3.1416
    max_position: 3.1416
    max_effort: 6.0

  joint_4_controller:
    type: my_controller_pkg/ArmController
    joint: m_joint_4
    Kp: 1.0
    Ki: 0.01
    Kd: 0.1
    clamp_iMax: 100.0
    has_position_limits: true
    has_velocity_limits: false
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: true
    min_position: -3.1416
    max_position: 3.1416
    max_effort: 6.0

  joint_gripper_controller:
    type: my_controller_pkg/ArmController
    joint: m_joint_5
    Kp: 0.1
    Ki: 0.0001
    Kd: 0.01
    clamp_iMax: 100.0
    has_position_limits: true
    has_velocity_limits: false
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: true
    min_position: -3.1416
    max_position: 3.1416
    max_effort: 6.0
