
# The PID gains and controller settings must be saved in a yaml file that gets loaded
# to the param server via the roslaunch file (mobile_control.launch).

mobile:
  # Publish all joint states -----------------------------------
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50 
  
  #   MobileController, which we have created, uses velocity joint interface instead of effort joint interface,
  # but the velocity joint interface and controller created onto the effort joint interface,
  # just like in the WheelController that we have designed.
  skidsteer_controller:
    type: "my_controller_pkg/MobileController"
    left_wheel: ['wljf', 'wljb']
    right_wheel: ['wrjf', 'wrjb']
    publish_rate: 50.0
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    cmd_vel_timeout: 20.0 
    wheel_separation: 0.287
    wheel_radius: 0.045
    base_frame_id: base_footprint
    odom_frame_id: odom
    publish_cmd: true
    linear:
      x:
        has_velocity_limits: true
        min_velocity: -0.5
        max_velocity: 1.0
        has_acceleration_limits: true
        min_acceleration: -0.5
        max_acceleration: 1.0
        has_jerk_limits: true
        max_jerk: 5.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 2.0
        has_jerk_limits: true
        max_jerk: 10.0

  # Wheel Controllers ---------------------------------------
  # leftFrontWheel_controller:
  #   type: my_controller_pkg/WheelController
  #   joint: wljf
  #   Kp: 1.0
  #   Ki: 0.0025
  #   Kd: 0.0
  #   iMax: 20.0
  #   has_position_limits: false
  #   has_velocity_limits: true
  #   has_acceleration_limits: false
  #   has_jerk_limits: false
  #   has_effort_limits: true
  #   max_velocity: 2.0
  #   max_effort: 6.0
  #   filter_constant: 20 # [Hz]
    
  # leftBackWheel_controller:
  #   type: my_controller_pkg/WheelController
  #   joint: wljb
  #   Kp: 1.0
  #   Ki: 0.0025
  #   Kd: 0.0
  #   iMax: 20.0
  #   has_position_limits: false
  #   has_velocity_limits: true
  #   has_acceleration_limits: false
  #   has_jerk_limits: false
  #   has_effort_limits: true
  #   max_velocity: 2.0
  #   max_effort: 6.0
  #   filter_constant: 20 # [Hz]

  # rightFrontWheel_controller:
  #   type: my_controller_pkg/WheelController
  #   joint: wrjf
  #   Kp: 1.0
  #   Ki: 0.0025
  #   Kd: 0.0
  #   iMax: 20.0
  #   has_position_limits: false
  #   has_velocity_limits: true
  #   has_acceleration_limits: false
  #   has_jerk_limits: false
  #   has_effort_limits: true
  #   max_velocity: 2.0
  #   max_effort: 6.0
  #   filter_constant: 20 # [Hz]

  # rightBackWheel_controller:
  #   type: my_controller_pkg/WheelController
  #   joint: wrjb
  #   Kp: 1.0
  #   Ki: 0.0025
  #   Kd: 0.0
  #   iMax: 20.0
  #   has_position_limits: false
  #   has_velocity_limits: true
  #   has_acceleration_limits: false
  #   has_jerk_limits: false
  #   has_effort_limits: true
  #   max_velocity: 2.0
  #   max_effort: 6.0
  #   filter_constant: 20 # [Hz]

  # Arm Controllers ---------------------------------------
  joint_1_controller:
    type: my_controller_pkg/ArmController
    joint: m_joint_1
    Kp: 65.0
    Ki: 0.065
    Kd: 6.5
    iMax: 100.0
    filter_constant: 100 # [Hz]
    has_position_limits: true
    has_velocity_limits: true
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: true
    min_position: -3.1416
    max_position: 3.1416
    min_velocity: -1.5
    max_velocity: 1.5
    max_effort: 6.0

  joint_2_controller:
    type: my_controller_pkg/ArmController
    joint: m_joint_2
    Kp: 65.0
    Ki: 0.065
    Kd: 6.5
    iMax: 100.0
    filter_constant: 100 # [Hz]
    has_position_limits: true
    has_velocity_limits: true
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: true
    min_position: -1.5708
    max_position: 1.5708
    min_velocity: -1.5
    max_velocity: 1.5
    max_effort: 6.0

  joint_3_controller:
    type: my_controller_pkg/ArmController
    joint: m_joint_3
    Kp: 50.0
    Ki: 0.05
    Kd: 5.0
    iMax: 100.0
    filter_constant: 100 # [Hz]
    has_position_limits: true
    has_velocity_limits: true
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: true
    min_position: -3.1416
    max_position: 3.1416
    min_velocity: -1.5
    max_velocity: 1.5
    max_effort: 6.0

  joint_4_controller:
    type: my_controller_pkg/ArmController
    joint: m_joint_4
    Kp: 2.0
    Ki: 0.002
    Kd: 0.2
    iMax: 100.0
    filter_constant: 100 # [Hz]
    has_position_limits: true
    has_velocity_limits: true
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: true
    min_position: -3.1416
    max_position: 3.1416
    min_velocity: -2.0
    max_velocity: 2.0
    max_effort: 6.0

  joint_5_controller:
    type: my_controller_pkg/ArmController
    joint: m_joint_5
    Kp: 2.0
    Ki: 0.002
    Kd: 0.2
    iMax: 100.0
    filter_constant: 100 # [Hz]
    has_position_limits: true
    has_velocity_limits: true
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: true
    min_position: -3.1416
    max_position: 3.1416
    min_velocity: -2.0
    max_velocity: 2.0
    max_effort: 6.0
