
# The PID gains and controller settings must be saved in a yaml file that gets loaded
# to the param server via the roslaunch file (mobile_control.launch).

mobile:
  # Publish all joint states -----------------------------------
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

#   # Effort Controllers ---------------------------------------
#   leftWheel_effort_controller:
#     type: effort_controllers/JointEffortController
#     joint: wljb
#     joint: wljf
#     pid: {p: 100.0, i: 0.1, d: 10.0}
#     #pid: {p: 50.0, i: 0.1, d: 0.0}
#   rightWheel_effort_controller:
#     type: effort_controllers/JointEffortController
#     joint: wrjb
#     joint: wrjf
#     pid: {p: 100.0, i: 0.1, d: 10.0}
#     #pid: {p: 50.0, i: 0.1, d: 0.0}

  joint_1_position_controller:
    type: position_controllers/JointPositionController
    joint: m_joint_1
    pid: {p: 100.0, i: 0.1, d: 10.0}

  joint_2_position_controller:
    type: position_controllers/JointPositionController
    joint: m_joint_2
    pid: {p: 100.0, i: 0.1, d: 10.0}

  joint_3_position_controller:
    type: position_controllers/JointPositionController
    joint: m_joint_3
    pid: {p: 100.0, i: 0.1, d: 10.0}

  joint_4_position_controller:
    type: position_controllers/JointPositionController
    joint: m_joint_4
    pid: {p: 100.0, i: 0.1, d: 10.0}

  joint_gripper_position_controller:
    type: position_controllers/JointPositionController
    joint: m_joint_5
    pid: {p: 100.0, i: 0.1, d: 10.0}
