# http://wiki.ros.org/base_local_planner
TrajectoryPlannerROS:

  # Robot Configuration Parameters
  max_vel_x: 0.5
  min_vel_x: 0.01

  max_vel_theta: 2.0
  min_vel_theta: -2.0
  min_in_place_vel_theta: 0.4

  acc_lim_x: 2.5
  acc_lim_theta: 3.2

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.10
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 10.0
  vx_samples: 20
  vtheta_samples: 40

  # Trajectory Scoring Parameters
  meter_scoring: true
  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.01
  heading_lookahead: 0.325
  dwa: true

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.01 #0.05

  # Differential-drive robot configuration
  holonomic_robot: false
  max_vel_y: 0.0
  min_vel_y: 0.0
  acc_lim_y: 0.0
  vy_samples: 0

  # cost_factor: 0.55
  # neutral_cost: 50
  # lethal_cost: 250
