max_obstacle_height: 0.60  # assume something like an arm is mounted on top of the robot

#robot_radius: 0.20  # distance a circular robot should be clear of the obstacle (kobuki: 0.18)
footprint: [[-0.2, -0.135], [0.2, -0.135], [0.2, 0.135],[-0.2, 0.135]]  # if the robot is not circular

footprint_padding: 0.0
transform_tolerance: 0.2

map_type: voxel

obstacle_layer:
    enabled: true
    publish_voxel_map: false
    obstacle_range: 3.0
    raytrace_range: 4.0
    track_unknown_space: false
    combination_method: 1
    unknown_threshold: 20
    z_voxels: 20
    max_obstacle_height: 0.60
    footprint_clearing_enabled: true
    observation_sources: scan
    scan:
        data_type: LaserScan
        topic: /mobile/laser/scan
        marking: true
        clearing: true
        min_obstacle_height: 0.15
        max_obstacle_height: 0.30

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
    enabled: true
    cost_scaling_factor: 10.0
    inflation_radius: 0.20

static_layer:
    enabled: true
    map_topic: "/map"
