# -- Warnings!
# -- do not set min_trans_vel to 0.0 otherwise dwa will always think translational velocities
# are non-negligible and small in place rotational velocities will be created.

DWAPlannerROS:

    global_frame_id: /map
    holonomic_robot: false

    # Robot Configuration Parameters
    acc_lim_x:  0.33 #1.00
    acc_lim_y:  0.00
    acc_lim_th: 0.66 #2.00
    acc_lim_theta: 3.20
    acc_limit_trans: 0.1

    max_trans_vel: 0.50
    min_trans_vel: 0.10

    max_vel_x: 0.50
    min_vel_x: -0.50
    max_vel_y: 0.00
    min_vel_y: 0.00
    max_rot_vel: 1.00
    min_rot_vel: -1.00
    
    # Goal Tolerance Parameters
    yaw_goal_tolerance: 0.05
    xy_goal_tolerance: 0.15
    latch_xy_goal_tolerance: true

    # Forward Simulation Parameters
    use_dwa: true
    sim_time: 1.0
    sim_granularity: 0.025
    angular_sim_granularity: 0.1
    vx_samples: 12
    vy_samples: 1
    vth_samples: 20

    # Trajectory Scoring Parameters
    meter_scoring: false
    path_distance_bias: 64.00
    goal_distance_bias: 32.00
    occdist_scale: 0.01
    forward_point_distance: 0.250 #0.325    
    stop_time_buffer: 0.20
    scaling_speed: 0.25
    max_scaling_factor: 0.20

    # Oscillation Prevention and Other Parameters
    oscillation_reset_dist: 0.05
    oscillation_reset_angle: 0.2
    trans_stopped_vel: 0.0
    rot_stopped_vel: 0.1
    prune_plan: true
    restore_defaults: false

    # Debugging
    publish_traj_pc : true
    publish_cost_grid_pc: true
