# -- Warnings!
# -- do not set min_trans_vel to 0.0 otherwise dwa will always think translational velocities
# are non-negligible and small in place rotational velocities will be created.

DWAPlannerROS:

    global_frame_id: /map
    holonomic_robot: false

    # Robot Configuration Limit Parameters
    acc_lim_x: 1.0
    acc_lim_y: 0.0
    acc_lim_th: 1.0

    max_vel_x: 0.55
    min_vel_x: 0.0
    max_vel_y: 0.0
    min_vel_y: 0.0
    max_rot_vel: 1.0
    min_rot_vel: 0.0

    max_trans_vel: 0.5
    min_trans_vel: 0.0
    
    # Goal Tolerance Parameters
    yaw_goal_tolerance: 0.15
    xy_goal_tolerance: 0.20
    latch_xy_goal_tolerance: true

    # Forward Simulation Parameters
    sim_time: 1.0
    sim_granularity: 0.025
    angular_sim_granularity: 0.025
    vx_samples: 12
    vy_samples: 1
    vth_samples: 20

    # Trajectory Scoring Parameters
    path_distance_bias: 64.0
    goal_distance_bias: 24.0
    occdist_scale: 0.05
    forward_point_distance: 0.325 
    stop_time_buffer: 0.2
    scaling_speed: 0.25
    max_scaling_factor: 0.2

    # Oscillation Prevention and Other Parameters
    oscillation_reset_dist: 0.05
    trans_stopped_vel: 0.1
    rot_stopped_vel: 0.1
    prune_plan: true
    restore_defaults: false

    # Debugging
    publish_traj_pc : false
    publish_cost_grid_pc: false
