shutdown_costmaps: false

planner_frequency: 1.0
planner_patience: 5.0

controller_frequency: 10.0
controller_patience: 15.0

oscillation_timeout: 10.0
oscillation_distance: 0.25

base_local_planner: "dwa_local_planner/DWAPlannerROS" # "teb_local_planner/TebLocalPlannerROS" # "dwa_local_planner/DWAPlannerROS"
base_global_planner: "global_planner/GlobalPlanner" 
  #alternatives: global_planner/GlobalPlanner, carrot_planner/CarrotPlanner
