<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertia    
            ixx="${m*(3*r*r+h*h)/12}" 
            ixy="0" 
            ixz="0"
            iyy="${m*(3*r*r+h*h)/12}" 
            iyz="0"
            izz="${m*r*r/2}" />
    </xacro:macro>
    <xacro:macro name="box_inertia" params="m x y z">
        <inertia    
            ixx="${m*(y*y+z*z)/12}" 
            ixy="0" 
            ixz="0"
            iyy="${m*(x*x+z*z)/12}" 
            iyz="0"
            izz="${m*(x*x+y*y)/12}" />
    </xacro:macro>
    <xacro:macro name="sphere_inertia" params="m r">
        <inertia    
            ixx="${2*m*r*r/5}" 
            ixy="0" 
            ixz="0"
            iyy="${2*m*r*r/5}" 
            iyz="0"
            izz="${2*m*r*r/5}" />
    </xacro:macro>

    <xacro:macro name="wheel" params="lr fb Tlr Tfb">

        <link name="w${lr}${fb}">
            <inertial>
                <origin 
                    xyz="0 0 0.005" 
                    rpy="0 0 0" />
                <mass 
                    value="${wheelMass}"/>
                <cylinder_inertia 
                    m="${wheelMass}" 
                    r="${wheelRadius}" 
                    h="${wheelWidth}"/>
            </inertial>
            <collision>
                <origin 
                    xyz="0 0 0" 
                    rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://mobile_description/meshes/w${lr}${fb}.STL" />
                </geometry>
            </collision>
            <visual>
                <origin 
                    xyz="0 0 0" 
                    rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://mobile_description/meshes/w${lr}${fb}.STL" />
                </geometry>
                <material name="black"/>
            </visual>
        </link>

        <joint name="w${lr}j${fb}" type="continuous">
            <parent link="chassis"/>
            <child link="w${lr}${fb}"/>
            <origin 
                xyz="${Tfb*0.09} ${Tlr*0.1385} ${0.0165+wheelRadius}" 
                rpy="1.5708 0 ${(Tlr+1)*1.5708}" />
            <axis 
                xyz="0 0 ${Tlr}" 
                rpy="0 0 0" />
            <limit 
                effort="100.0" 
                velocity="100.0"/>
            <dynamics damping="0.0" friction="0.0"/>
        </joint>

        <gazebo reference="w${lr}${fb}">
            <mu1 value="1.2"/>
            <mu2 value="1.2"/>
            <kp value="1.0E+7"/>
            <kd value="1.0E+0"/>
            <minDepth>0.001</minDepth>
            <maxVel>100.0</maxVel>
            <material>Gazebo/FlatBlack</material>
        </gazebo>

        <transmission name="${lr}${fb}_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="w${lr}j${fb}">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${lr}${fb}Motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>10</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>

</robot>